# Generated by Django 4.2 on 2023-12-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_participant_event_remove_participant_giver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultLottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver_name', models.CharField(max_length=100, verbose_name='Кто дарит')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Розыгрыш',
                'verbose_name_plural': 'Розыгрыши',
            },
        ),
    ]
