# Generated by Django 4.2 on 2023-12-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_resultlottery'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='bot.event'),
        ),
    ]
