# Generated by Django 4.2 on 2023-12-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_participant_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tg_chat_id',
            field=models.CharField(default='', max_length=200, verbose_name='Тг чат id'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='bot.event'),
        ),
    ]
