# Generated by Django 4.2 on 2023-12-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_resultlottery_giver_present_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultlottery',
            name='giver_present',
            field=models.CharField(max_length=100, verbose_name='Подарок Кто дарит'),
        ),
        migrations.AlterField(
            model_name='resultlottery',
            name='receiver_present',
            field=models.CharField(max_length=100, verbose_name='Подарок Получатель'),
        ),
    ]
